### PR TITLE
Ubuntu 18.10 LGTM build

### PR DESCRIPTION
**Pull request by jbj**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [x] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:
I'm about to update the build environment on lgtm.com from Ubuntu 18.04 to 18.10, and this breaks your project. It appears that [libgit2 now depends on libmbedtls](https://packages.ubuntu.com/cosmic/libgit2-dev), and it [didn't do this before](https://packages.ubuntu.com/bionic/libgit2-dev). By default, your project links statically with libgit2, but static linking requires specifying all dependencies of the library, and your builds doesn't specify libmbedtls. I'm working around the problem here by passing the `LIBGIT2_DYNAMIC` option to your CMake script, which makes libgit2 dynamically linked, and dynamically linked libraries don't need to have their transitive dependencies specified.

I'm taking this opportunity to make a few more changes to `.lgtm.yml` to prevent problems in the future when we upgrade the build environment.

### Changes made:

1. Pass `-DLIBGIT2_DYNAMIC` to CMake to allow building on Ubuntu 18.10.
2. Pass `-DNO_DOCS=ON` to avoid building things we don't need.
3. Pass `DCMAKE_VERBOSE_MAKEFILE=ON` for ease of debugging build problems.
4. Remove the manual list of dependency packages and instead rely on LGTM's automatic dependency detection. The manual dependency list contained version numbers and was therefore not likely to keep working over time. The automatic dependency detection only works in the `configure` and `index` steps, so I moved some lines from `after_prepare` to `configure`.

### Additional information:

Without this fix, we get linker errors like the following.

```
[2019-03-21 16:14:31] [build] [ 65%] Linking CXX executable subsurface
[2019-03-21 16:14:36] [build] /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libgit2.a(mbedtls.c.o): in function `shutdown_ssl':
[2019-03-21 16:14:36] [build] (.text+0x68): undefined reference to `mbedtls_x509_crt_free'
[2019-03-21 16:14:36] [build] /usr/bin/ld: (.text+0x8b): undefined reference to `mbedtls_ctr_drbg_free'
[2019-03-21 16:14:36] [build] /usr/bin/ld: (.text+0xa7): undefined reference to `mbedtls_ssl_config_free'
[2019-03-21 16:14:36] [build] /usr/bin/ld: (.text+0xcf): undefined reference to `mbedtls_entropy_free'
[2019-03-21 16:14:36] [build] /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libgit2.a(mbedtls.c.o): in function `verify_server_cert':
[2019-03-21 16:14:36] [build] (.text+0x14d): undefined reference to `mbedtls_ssl_get_verify_result'
...
[2019-03-21 16:14:36] [build] collect2: error: ld returned 1 exit status
```

### Mentions:

@dirkhh

### CODE REVIEW

**Review by dirkhh — APPROVED** [review]
Jonas, thanks for your submission! Having the LGTM team look at the impact of a distro change on the projects that use LGTM is rather spectacular. I'm impressed.
The changes make sense - I simply modeled what I had there on how I could get things to build on Ubuntu 18.04 (because as I mentioned before in the forums, our build system typically makes some assumptions that aren't true on LGTM). But if this works it's of course much simpler and therefore easier to maintain.
Much appreciated.

**Comment by dirkhh** [comment]
I will wait for the checks to pass before merging.
